config/routes.rb
Rails.application.routes.draw do
  root :to => "home#top"
  post "teachers/:id/update" => "teachers#update"
  get "teachers/:id/edit" => "teachers#edit"
  post "teachers/create" => "teachers#create"
  get "teachers/signup" => "teachers#new"
  get "teachers/index" => "teachers#index"
  get "teachers/:id" => "teachers#show"
  post "teachers/login" => "teachers#login"
  post "teachers/logout" => "teachers#logout"
  get "teachers/login" => "teachers#login_form"
  
  get "login" => "users#login_form"
  post "login" => "users#login"
  post "logout" => "users#logout"
  post "users/:id/update" => "users#update"
  get "users/:id/edit" => "users#edit"
  post "users/create" => "users#create"
  get "signup" => "users#new"
  get "users/:id" => "users#show"
  
  #お問い合わせフォーム
  resources :teachers do
    resources :inquiry
  end
  post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  include ActiveModel::Model
  
  attr_accessor :body
  
  belongs_to :teacher
  belongs_to :user
end

app/models/inquiry_mailer.rb
class InquiryMailer < ApplicationRecord
 
  def send_mail(inquiry)
    @teacher = Teacher.find(id: params[:teacher_id])
    @inquiry = inquiry
    mail(from: @current_user.email,
        to: @teacher.email,
        subject:  'お問い合わせ内容')
  end
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_secure_password
  # nameカラムに関するバリデーションを作成してください
  validates :name, {presence:true}
  # emailカラムに関するバリデーションを作成してください
  validates :email, {presence:true, uniqueness: true}
  validates :password, {presence: true}
  
  has_many :inquiry
  
end

app/models/user.rb
class User < ApplicationRecord
 has_secure_password
  validates :name, {presence:true}
  validates :email, {presence:true, uniqueness: true}
  validates :password, {presence: true}
  
 has_many :inquiry
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   # before_actionにset_current_userメソッドを指定してください
  before_action :set_current_teacher
  before_action :set_current_user
  
  # set_current_userメソッドを定義してください
  def set_current_teacher
    @current_teacher = Teacher.find_by(id: session[:teacher_id])
  end
  
  def authenticate_teacher
    if @current_teacher == nil
      flash[:notice] = "ログインが必要です"
      redirect_to("/login")
    end
  end
  
  def forbid_login_teacher
    if @current_teacher
      flash[:notice] = "すでにログインしています"
      redirect_to("/teachers/#{@current_teacher.id}/edit")
    end
  end
  
  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end
  
  def authenticate_user
    if @current_user == nil
      flash[:notice] = "ログインが必要です"
      redirect_to("/login")
    end
  end
  
  def forbid_login_user
    if @current_user
      flash[:notice] = "すでにログインしています"
      redirect_to("/posts/index")
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :forbid_login_teacher, {only: [:top]}
  def top
  end
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def new
    # 入力画面を表示
    @inquiry = Inquiry.new
    render :action => 'new'
  end
 
  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(inquiry_params)
    # if @inquiry.valid?
    #   # OK。確認画面を表示
    #   render :action => 'confirm'
    # else
    #   # NG。入力画面を再表示
    #   render :action => 'new'
    # end
  end
 
  def thanks
    # メール送信
    @inquiry = Inquiry.new(inquiry_params)
    InquiryMailer.send_email(@inquiry).deliver
 
    # 完了画面を表示
    render :action => 'thanks'
  end
  
  private
  def inquiry_params
    params.require(:inquiry).permit(:body, :teacher_id, :user_id)
  end
end

app/controllers/inquiry_mailer_controller.rb
class InquiryMailerController < ApplicationController
  def send_mail(inquiry)
    @teacher = Teacher.find(id: params[:teacher_id])
    @inquiry = inquiry
    mail(from: @current_user.email,
        to: @teacher.email,
        subject:  'お問い合わせ内容')
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_teacher, {only: [:edit, :update]}
  before_action :forbid_login_teacher, {only: [:new, :create, :login_form, :login]}
  before_action :ensure_correct_teacher, {only: [:edit, :update]}

  def index
    @teachers = Teacher.order("updated_at DESC").page(params[:page]).per(24)
    @teacher = Teacher.new(teacher_params)
  end
  
  def new
    @teacher = Teacher.new
  end
  
  def show
    @teacher = Teacher.find_by(id: params[:id])
  end
  
  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.save
      flash[:notice] = "家庭教師登録が完了しました"
      redirect_to("/teachers/#{@teacher.id}/edit")
    else
      render("teachers/new")
    end
  end
  
  def edit
    @teacher = Teacher.find_by(id: params[:id])
  end
  
  # updateアクションを作成してください
  def update
    @teacher = Teacher.find_by(id: params[:id])
    
    if params[:image]
      @teacher.img = "#{@teacher.id}.jpg"
      image = params[:image]
      File.binwrite("public/teacher_images/#{@teacher.img}", image.read)
    end
    
    if @teacher.update(teacher_params)
      flash[:notice] = "ユーザー情報を編集しました"
      redirect_to("/teachers/#{@teacher.id}")
    else
      flash[:notice] = "編集できませんでした"
      render("teachers/edit")
    end
  end
  
  def login_form
  end
  
  def login
    @teacher = Teacher.find_by(email: params[:email])
    if @teacher && @teacher.authenticate(params[:password])
      session[:teacher_id] = @teacher.id
      flash[:notice] = "ログインしました"
      # redirect_toの場合ははじめにスラッシュを入れる
      redirect_to("/teachers/#{@teacher.id}/edit")
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      @email = params[:email]
      @password = params[:password]
      
      render("teachers/login_form")
    end
  end
  
  def logout
    session[:teacher_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to("/")
  end
  
  # ensure_correct_userを定義してください
  def ensure_correct_teacher
    if @current_teacher.id != params[:id].to_i
      flash[:notice] = "権限がありません"
      redirect_to("/teachers/login")
    end
  end
  
  private
  def teacher_params
    params.permit(:name, :email, :password, :nickname, :gender, :university, :faculty, :department, :wage, :trafficwage, :time, :prefecture, :region, :profile, :message)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, {only: [:show, :edit, :update]}
  before_action :forbid_login_user, {only: [:new, :create, :login_form, :login]}
  # before_actionにensure_correct_userメソッドを指定してください
  before_action :ensure_correct_user, {only:[:edit, :update]}
  
  
  def show
    @user = User.find_by(id: params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(
      name: params[:name],
      email: params[:email],
      password: params[:password]
    )
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "ユーザー登録が完了しました"
      redirect_to("/users/#{@user.id}")
    else
      render("users/new")
    end
  end
  
  def edit
    @user = User.find_by(id: params[:id])
  end
  
  def update
    @user = User.find_by(id: params[:id])
    @user.name = params[:name]
    @user.email = params[:email]
    
    if @user.save
      flash[:notice] = "ユーザー情報を編集しました"
      redirect_to("/users/#{@user.id}")
    else
      render("users/edit")
    end
  end
  
  def login_form
  end
  
  def login
    @user = User.find_by(email: params[:email])
    
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました"
      redirect_to("/teachers/index")
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      @email = params[:email]
      @password = params[:password]
      render("users/login_form")
    end
  end
  
  def logout
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to("/login")
  end
  
  # ensure_correct_userを定義してください
  def ensure_correct_user
    if @current_user.id != params[:id].to_i
      flash[:notice] ="権限がありません"
      redirect_to("/posts/index")
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/inquiry_mailer_helper.rb
module InquiryMailerHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<div class="top-wrapper">
  
    <a href="#" class="title">Study Partner</a>
    <h5>スタディパートナーは生徒と家庭教師をつなぐ、個人契約のマッチングサイトです</h5>
    <p>入会金・年会費・管理費は一切かかりません</p>
    <%= link_to "さっそく家庭教師を探してみよう", "/teachers/index", class:"btn-square-shadow" %>
</div>

<div class="index-wrapper">
  
  <h4>Study Partnerが選ばれる理由</h4>
  
    <h6><span class="marker-yellow">　1.「おトク」で「安心」な料金</span></h6>
    <p>大手予備校や塾では入会金・年会費・管理費として数十万円かかりますが、
    スタディパートナーではそれらの料金は一切発生致しません。
    <br>
    サイト利用料として9,800円が発生致しますが、利用料をお支払いいただければ、
    何人でも何通でもメッセージを送ることができます。<br>
    お支払い情報に関しましては、国内最大手の決済代行会社にて厳重に管理され、
    トラブルなしの安心決済システムになっています。</p>
  
    <h6><span class="marker-yellow">　2.希望の授業を「好きな場所」「好きな時間帯」で受けられる</span></h6>
    <p>生徒に合ったペースの授業を家庭教師と相談しながら受けられるのが、予備校や塾にはない家庭教師のメリットです。<br>
      「テスト直前や長期休暇の間は、授業をもっと多くしてほしい」という声にも、家庭教師なら応えることができます。
    </p>
  
    <h6><span class="marker-yellow">　3.「お兄さん・お姉さん」のような家庭教師が選び放題</span></h6>
    <p>やる気や成績に大きな影響を与える要因の一つに家庭教師との相性があります。<br>
      スタディパートナーでは現役大学生の中でも「楽しく勉強できる！」「理解できるまで何度でも教えてもらえる！」先生にこだわっています。<br>
      何人でも何通でもメッセージをお送りすることができますので、お子さんの性格や趣味に合わせて、ベストパートナーを見つけてみてください！
    </p>
  <%= link_to "家庭教師を探してみる", " /teachers/index",class:"btn-square-shadow" %>
</div>




<div class="recruit-wrapper">
  <h4>家庭教師募集中</h4>
    <h6>生徒に勉強の楽しさを教えてあげられる先生<br>
    生徒の気持ちを理解し、根気強く向き合える先生を募集しています</h6>
    
    <%= link_to "家庭教師に登録する", "/teachers/signup", class:"btn-square-shadow" %>
</div>

app/views/inquiry/confirm.html.erb
<%= form_for @inquiry, :url => inquiry_thanks_path do |f| %>
   <p>お問い合わせ内容</p>
    <%= f.hidden_field :body %>
    <%= simple_format(@inquiry.body) %>
    <%= f.submit '送信' %>
<% end %>

app/views/inquiry/new.html.erb
<%= form_for @inquiry, :url => inquiry_confirm_path do |f| %>
  <p>お問い合わせ</p>
  <%= f.text_area :body %>
  <%= f.submit '確認' %>
<% end %>

app/views/inquiry/thanks.html.erb
<div class="page-header">
  <h1>お問い合わせ</h1>
</div>
<p>
  お問い合わせいただきありがとうございます。他の先生にも相談してみましょう。
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudyPartner</title>
    <meta name="description" content="生徒と家庭教師をつなぐ、個人契約のマッチングサイトです。入会金・年会費・管理費全て無料でご利用いただけます。">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <div class="container">
      <div class="header-left">
        <a href="/">Study Partner</a>
        <!-- 後で画像を入れる-->
      </div>
      <div class="header-right">
        <% if @current_teacher %>
          <ul>
            <li><%= link_to "マイページ","/teachers/#{@current_teacher.id}" %></li>
            <li><%= link_to "基本情報の編集","/teachers/#{@current_teacher.id}/edit" %></li>
            <li><%= link_to 'ログアウト',teachers_logout_path, method: :post%></li>
          </ul>
        <% elsif @current_user %>
        <ul>
          <li><%= link_to "家庭教師をさがす","/teachers/index"%></li>
          <li><%= link_to "マイページ","/users/#{@current_user.id}"%></li>
          <li><%= link_to "基本情報の編集","/users/#{@current_user.id}/edit"%></li>
          <li><%= link_to "ログアウト", logout_path, method: :post%></li>
        </ul>
        <% else %>
          <ul>
            <li><%= link_to("新規登録(生徒用)", signup_path) %></li>
            <li><%= link_to("ログイン(生徒用)", login_path, method: :post) %></li>
            <li><%= link_to("新規登録(先生用)", teachers_signup_path) %></li>
            <li><%= link_to("ログイン(先生用)", teachers_login_path, method: :post) %></li>
          </ul>
        <% end %>
      </div>
    </div>
    
  </header>
    <!--flash文の追加-->
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    
    <%= yield %>
  
    <footer>
          <div class="container">
            <div class="footer-left">
                <h5> Study Partner</h5>
                <p>スタディパートナーは生徒と家庭教師をつなぐ、個人契約のマッチングサイトです。</p>
                  <div class="footer-copyright">
                    <p>© 2019 Study Partner</p>
                    <a href="#!">More Links</a>
                  </div>
              </div>
              <div class="footer-right">
                <ul>
                  <li><a href="#!">お問い合わせ</a></li>
                  <li><a href="#!">利用規約</a></li>
                  <li><a href="#!">プライバシーポリシー</a></li>
                  <li><a href="#!">特定商取引法に基づく表記</a></li>
                </ul>
              </div>
            </div>
          </div>
          
    </footer>
  </body>
</html>

app/views/teachers/edit.html.erb
<div class="main users-edit">
  <div class="container">
    <div class="form-heading">アカウント編集</div>
    <div class="form users-form">
      <div class="form-body">
        <!-- エラーメッセージを表示するためのHTMLを貼り付けてください -->
        <% @teacher.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>
        
        <!-- フォームの送信先を指定してください -->
        <%= form_tag("/teachers/#{@teacher.id}/update", {multipart: true}) do %>
          <tr>
            <td>本名(非公開)</td>
            <td><input name="name" value="<%= @teacher.name %>"></td>
          </tr>
          
          <tr>
            <td>画像</td>
            <td><input name="img" type="file" value="<%= @teacher.img %>"></td>
          </tr>
          
          <tr>
            <td>メールアドレス（連絡用）</td>
            <td><input name="email" value="<%= @teacher.email %>"></td>
          </tr>
          
          <tr>
            <td>パスワード（非公開）</td>
            <td><input name="password" type="password" value="<%= @teacher.password %>"></td>
          </tr>
          
          <tr>
            <td>ニックネーム（公開）</td>
            <td><input name="nickname" value= "<%= @teacher.nickname %>"></td>
          </tr>
          
          <tr>
            <td>性別</td>
            <td>男性<input type="radio" name="gender" value="男性"></td>
            <td>女性<input type="radio" name="gender" value="女性"></td>
          </tr>
          
          <tr>
            <td>大学名</td>
            <td><input name="university" value="<%= @teacher.university %>"></td>
          </tr>
          
          <td>学部</td>
            <td><input name="faculty" value="<%= @teacher.faculty %>"></td>
          </tr>
          
          <tr>
            <td>学科</td>
            <td><input name="department" value="<%= @teacher.department %>"></td>
          </tr>
          
          <tr>
            <td>時給</td>
            <td><input name="wage" value="<%= @teacher.wage %>">円/時間</td>
          </tr>
          
          <tr>
            <td>交通費</td>
            <td><input name="trafficwage"  type="checkbox" value="希望">希望</td>
          </tr>
          
          <tr>
            <td>指導可能時間</td>
            <td><input name="time" placeholder="例）月曜16:00から、水曜19:00から可能です" value="<%= @teacher.time %>"></td>
          </tr>
          
          <tr>
            <td>都道府県選択</td>
            <td>
              <select name="prefecture">
          <option value="" selected>都道府県</option>
          <option value="北海道">北海道</option>
          <option value="青森県">青森県</option>
          <option value="岩手県">岩手県</option>
          <option value="宮城県">宮城県</option>
          <option value="秋田県">秋田県</option>
          <option value="山形県">山形県</option>
          <option value="福島県">福島県</option>
          <option value="茨城県">茨城県</option>
          <option value="栃木県">栃木県</option>
          <option value="群馬県">群馬県</option>
          <option value="埼玉県">埼玉県</option>
          <option value="千葉県">千葉県</option>
          <option value="東京都">東京都</option>
          <option value="神奈川県">神奈川県</option>
          <option value="新潟県">新潟県</option>
          <option value="富山県">富山県</option>
          <option value="石川県">石川県</option>
          <option value="福井県">福井県</option>
          <option value="山梨県">山梨県</option>
          <option value="長野県">長野県</option>
          <option value="岐阜県">岐阜県</option>
          <option value="静岡県">静岡県</option>
          <option value="愛知県">愛知県</option>
          <option value="三重県">三重県</option>
          <option value="滋賀県">滋賀県</option>
          <option value="京都府">京都府</option>
          <option value="大阪府">大阪府</option>
          <option value="兵庫県">兵庫県</option>
          <option value="奈良県">奈良県</option>
          <option value="和歌山県">和歌山県</option>
          <option value="鳥取県">鳥取県</option>
          <option value="島根県">島根県</option>
          <option value="岡山県">岡山県</option>
          <option value="広島県">広島県</option>
          <option value="山口県">山口県</option>
          <option value="徳島県">徳島県</option>
          <option value="香川県">香川県</option>
          <option value="愛媛県">愛媛県</option>
          <option value="高知県">高知県</option>
          <option value="福岡県">福岡県</option>
          <option value="佐賀県">佐賀県</option>
          <option value="長崎県">長崎県</option>
          <option value="熊本県">熊本県</option>
          <option value="大分県">大分県</option>
          <option value="宮崎県">宮崎県</option>
          <option value="鹿児島県">鹿児島県</option>
          <option value="沖縄県">沖縄県</option>
          </select>
            </td>
          </tr>
          
          <tr>
            <td>授業可能地域</td>
            <td><input name="region" placeholder="例）JR中央線沿線、都営新宿線沿線" value="<%= @teacher.region%>"></td>
          </tr>
          
          <tr>
            <td>プロフィール・趣味</td>
            <td><input name="profile" type="text" placeholder="経歴・趣味を入力してください"value="<%= @teacher.profile %>"></td>
          </tr>
          
          <tr>
            <td>メッセージ</td>
            <td><input name="message" type="text" placeholder="メッセージを入力すると応募率が高くなります"　value="<%= @teacher.message %>"><br></td>
          </tr>
        
          <!--ここから先はリリース後に編集する-->
          <!--<tr>-->
          <!--  <td>指導可能時間</td>-->
          <!--  <table>-->
          <!--    <tr>-->
          <!--      <td>曜日/時間</td>-->
          <!--      <td>月曜</td>-->
          <!--      <td>火曜</td>-->
          <!--      <td>水曜</td>-->
          <!--      <td>木曜</td>-->
          <!--      <td>金曜</td>-->
          <!--      <td>土曜</td>-->
          <!--      <td>日曜</td>-->
          <!--    </tr>-->
          <!--    <tr>-->
          <!--      <td>午前中</td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="mon1"></td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="tue1"></td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="wed1"></td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="thu1"></td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="fri1"></td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="sat1"></td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="sun1"></td>-->
          <!--    </tr>-->
          <!--    <tr>-->
          <!--      <td>13:00~16:00</td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="mon2"></td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="tue2"></td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="wed2"></td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="thu2"></td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="fri2"></td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="sat2"></td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="sun2"></td>-->
          <!--    </tr>-->
          <!--    <tr>-->
          <!--      <td>16:00~19:00</td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="mon3"></td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="tue3"></td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="wed3"></td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="thu3"></td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="fri3"></td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="sat3"></td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="sun3"></td>-->
          <!--    </tr>-->
          <!--    <tr>-->
          <!--      <td>19:00~22:00</td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="mon4"></td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="tue4"></td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="wed4"></td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="thu4"></td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="fri4"></td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="sat4"></td>-->
          <!--      <td><input type="checkbox" name="time[day_of_the_week][]" value="sun4"></td>-->
          <!--    </tr>-->
          <!--  </table>-->
          <!--<tr>-->
          
          <input type="submit" value="保存">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/teachers/index.html.erb
<div class="main users-index">
  <div class="container">
    <h1 class="users-heading">家庭教師一覧</h1>
   
    <% @teachers.each do |teacher| %>
      <div class="card">
        
        <%= teacher.img %>
        <%= teacher.nickname %>
        <%= teacher.gender %>
        <%= teacher.university %>
       <!--teacherに合わせて@teacherではなくteacher.idでかく-->
        <%= link_to "詳細を見る","/teachers/#{teacher.id}" %>
      </div>
    <% end %>
    <%= paginate(@teachers) %>
  </div>
</div>

app/views/teachers/login_form.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">ログイン</div>
    <div class="form users-form">
      <div class="form-body">
        <!-- form_tagメソッドを追加してください -->
        <%= form_tag(teachers_login_path) do %>
          <p>メールアドレス</p>
          <!-- name属性を追加してください -->
          <input name="email" value="<%= @email %>">
          <p>パスワード</p>
          <!-- name属性を追加してください -->
          <input type="password" name="password" value="<%= @password %>">
          <input type="submit" value="ログイン">
        <!-- form_tag用のendを追加してください -->
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/teachers/new.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">新規ユーザー登録</div>
    <div class="form users-form">
      <div class="form-body">
        <!-- エラーメッセージを表示するためのHTMLを貼り付けてください -->
        <% @teacher.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>
        
        <%= form_tag("/teachers/create") do %>
          <p>ユーザー名</p>
          <!-- value属性を用いて、初期値を設定してください -->
          <input name="name" value="<%= @teacher.name %>">
          <p>メールアドレス</p>
          <!-- value属性を用いて、初期値を設定してください -->
          <input name="email" value="<%= @teacher.email %>">
          <p>パスワード</p>
          <!-- パスワード用のフォームを追加してください -->
          <input type="password" name="password" value="<%= @teacher.password %>">
          <input type="submit" value="新規登録">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/teachers/show.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
        <%= @teacher.img %>
        <%= @teacher.nickname %>
        <%= @teacher.gender %>
        <%= @teacher.university %>
         <%= @teacher.faculty %>
        <%= @teacher.department %>
        <%= @teacher.wage %>
        <%= @teacher.trafficwage %>
        <%= @teacher.time %>
        <%= @teacher.prefecture %>
        <%= @teacher.region %>
        <%= @teacher.profile %>
        <%= @teacher.message %>
        
        <% if @current_user %>
          <%= link_to "この先生に相談する" ,new_teacher_inquiry_path(@teacher) %>
          <%= link_to "戻る", "/teachers/index" %>
        <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="main users-edit">
  <div class="container">
    <div class="form-heading">アカウント編集</div>
    <div class="form users-form">
      <div class="form-body">
        <% @user.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>
      
        <%= form_tag("/users/#{@user.id}/update", {multipart: true}) do %>
          <p>ユーザー名</p>
          <input name="name" value="<%= @user.name %>">
          <p>メールアドレス</p>
          <input name="email" value="<%= @user.email %>">
          <input type="submit" value="保存">
        <% end %>
      </div>
    </div>
  </div>
</div>